### ISSUE TITLE
scrap.py 실행오류 

### ISSUE THREAD

**Issue by Re-st** [NewWays-TechForImpactKAIST/main#12]
credentials.json을 구글에서 만들어서 다운받은 후 scrap.py 돌리니 아래 오류가 납니다.
```  
gun@(server):~/techforimpact$ python3 ./scrap.py 
Traceback (most recent call last):
  File "/home/gun/techforimpact/./scrap.py", line 174, in <module>
    main()
  File "/home/gun/techforimpact/./scrap.py", line 159, in main
    client: gspread.client.Client = google_authorization()
  File "/home/gun/techforimpact/./scrap.py", line 38, in google_authorization
    flow= InstalledAppFlow.from_client_secrets_file('credentials.json', SCOPES)
  File "/home/gun/.local/lib/python3.10/site-packages/google_auth_oauthlib/flow.py", line 201, in from_client_secrets_file
    return cls.from_client_config(client_config, scopes=scopes, **kwargs)
  File "/home/gun/.local/lib/python3.10/site-packages/google_auth_oauthlib/flow.py", line 159, in from_client_config
    raise ValueError("Client secrets must be for a web or installed app.")
ValueError: Client secrets must be for a web or installed app.
 ```
일단 [인터넷의 gspread 사용법](https://greeksharifa.github.io/references/2023/04/10/gspread-usage/) 대로 따라가서 credentials.json을 만들긴 했는데, client_email 키를 스프레드시트에 등록하는 부분에서 (전국 기초의원 스프레드시트를 직접 소유하는 게 아니니까)  막혔습니다.

혹시 제 credentials.json 이 구조가 잘못된 건가요? 
```
{
  "type": "service_account",
  "project_id": 
  "private_key_id": 
  "private_key": "-----BEGIN PRIVATE KEY-----\n( ... )\n-----END PRIVATE KEY-----\n",
  "client_email": 
  "client_id": 
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": 
  "universe_domain": "googleapis.com"
}
```

**Comment by Re-st** [comment]
![image](https://github.com/NewWays-TechForImpactKAIST/main/assets/42648067/db1ebe18-7763-4c70-9a92-5631c768f9ae)
이렇게 공유요청 보내면 되나요?

**Comment by pingpingy1** [comment]
앗 서비스 계정이 아니라 OAuth 2.0 클라이언트 ID로 생성해야 합니다! 생성 후 [구글 클라우드](https://console.cloud.google.com/apis/) -> 사용자 인증 정보 -> 클라이언트 보안 비밀번호 JSON 다운로드 로 다운로드 하시면 됩니다.
![image](https://github.com/NewWays-TechForImpactKAIST/main/assets/94441510/20e79778-1ea8-491f-a138-2c949b059a47)

정상적으로 다운로드 되었다면 {"installed": {"client_id": ...}}로 시작할 겁니다.

**Comment by Re-st** [comment]
감사합니다!
